# Generated by Django 5.2.6 on 2026-02-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
    ]
