# Generated by Django 5.2.6 on 2026-02-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirement',
        ),
    ]
